/**
 * safety.ts  —  GET /api/medicine/safety
 *
 * Returns a structured MedicineSafetyProfile for any medicine by name.
 *
 * Pipeline:
 *   1. Normalise query → resolve generic name from our medicines table.
 *   2. Check Supabase `medicine_safety_profiles` cache.
 *   3. If cache miss:  fetch RAG context from OpenFDA, then call LLM.
 *   4. Persist result to Supabase so all future requests are free/instant.
 *   5. Return JSON in the exact shape the frontend MedicineSafetyPanel expects.
 */

import { Router, Request, Response } from "express";
import { z } from "zod";
import { supabase } from "../db/client";
import { redisClient } from "../utils/redis";
import logger from "../utils/logger";
import { fetchOpenFdaContext } from "../services/openfda.service";
import { generateSafetyProfile } from "../services/llm.service";
import { scanQueryLimiter } from "../middleware/rateLimit";

const router = Router();

// ── Redis key prefix ──────────────────────────────────────────────────────────
const REDIS_PREFIX = "medicine_safety:";
const REDIS_TTL_SEC = 60 * 60 * 24; // 24 hours

// ── Query schema ──────────────────────────────────────────────────────────────
const querySchema = z.object({
    q: z.string().trim().min(2).max(200),
});

// ── Helper: resolve a fuzzy user query to a generic name ─────────────────────
async function resolveGenericName(query: string): Promise<string> {
    // Try full-text search in our medicines table first
    const { data } = await supabase.rpc("search_medicines_text", {
        query_text: query,
        match_count: 1,
    });

    if (data?.[0]?.generic_name) {
        return (data[0].generic_name as string).toLowerCase().trim();
    }

    // Fallback: use the query itself as the generic name (LLM will figure it out)
    return query.toLowerCase().trim();
}

// ── Helper: fetch from Supabase DB cache ─────────────────────────────────────
async function getDbCachedProfile(genericName: string) {
    const { data, error } = await supabase
        .from("medicine_safety_profiles")
        .select("profile_json, updated_at")
        .eq("generic_name", genericName)
        .maybeSingle();

    if (error) {
        logger.warn(`[safety] DB cache read error for "${genericName}": ${error.message}`);
        return null;
    }

    if (!data?.profile_json) return null;

    const updatedAtMs = new Date(data.updated_at).getTime();
    const nowMs = Date.now();
    const isFresh = Number.isFinite(updatedAtMs) && updatedAtMs <= nowMs && nowMs - updatedAtMs < REDIS_TTL_SEC * 1000;

    return isFresh ? data.profile_json : null;
}

// ── Helper: persist profile to Supabase DB cache ─────────────────────────────
async function setDbCachedProfile(genericName: string, profile: object) {
    const { error } = await supabase.from("medicine_safety_profiles").upsert(
        {
            generic_name: genericName,
            profile_json: profile,
            updated_at: new Date().toISOString(),
        },
        { onConflict: "generic_name" }
    );

    if (error) {
        logger.warn(`[safety] DB cache write error for "${genericName}": ${error.message}`);
    }
}

/**
 * @openapi
 * /api/medicine/safety:
 *   get:
 *     tags:
 *       - Medicine Safety
 *     summary: Get structured safety profile for any medicine
 *     description: >
 *       Returns side effects, age-based dosage, dietary cues, and storage
 *       information for a medicine. Data is generated by an LLM (Gemini 2.0
 *       Flash with Groq LLaMA 3.1 fallback) grounded with OpenFDA reference text
 *       and cached in Supabase for all future requests.
 *     parameters:
 *       - in: query
 *         name: q
 *         required: true
 *         schema:
 *           type: string
 *         description: Medicine name (brand or generic, e.g. "Telma-R" or "telmisartan")
 *     responses:
 *       200:
 *         description: Safety profile found/generated
 *       400:
 *         description: Missing or invalid query parameter
 *       503:
 *         description: Both LLM providers unavailable
 */
router.get("/", scanQueryLimiter, async (req: Request, res: Response): Promise<void> => {
    // ── 1. Validate input ─────────────────────────────────────────────────────
    const parsed = querySchema.safeParse(req.query);
    if (!parsed.success) {
        res.status(400).json({ error: "Query parameter 'q' is required (2–200 chars)." });
        return;
    }
    const { q } = parsed.data;

    // ── 2. Resolve to canonical generic name ─────────────────────────────────
    const genericName = await resolveGenericName(q);
    logger.info(`[safety] Query "${q}" → resolved generic: "${genericName}"`);

    const redisCacheKey = `${REDIS_PREFIX}${genericName}`;

    // ── 3. Redis L1 cache ─────────────────────────────────────────────────────
    try {
        if (redisClient.isOpen) {
            const cached = await redisClient.get(redisCacheKey);
            if (cached) {
                logger.info(`[safety] Redis HIT for "${genericName}"`);
                res.setHeader("X-Cache", "HIT");
                res.setHeader("X-Cache-Source", "redis");
                res.json(JSON.parse(cached));
                return;
            }
        }
    } catch (err) {
        logger.warn(`[safety] Redis read error: ${err instanceof Error ? err.message : err}`);
    }

    // ── 4. Supabase L2 cache ──────────────────────────────────────────────────
    const dbCached = await getDbCachedProfile(genericName);
    if (dbCached) {
        logger.info(`[safety] Supabase DB HIT for "${genericName}"`);

        // Backfill Redis
        try {
            if (redisClient.isOpen) {
                await redisClient.set(redisCacheKey, JSON.stringify(dbCached), {
                    EX: REDIS_TTL_SEC,
                });
            }
        } catch {
            /* best-effort */
        }

        res.setHeader("X-Cache", "HIT");
        res.setHeader("X-Cache-Source", "supabase");
        res.json(dbCached);
        return;
    }

    // ── 5. Cache miss → RAG + LLM generation ─────────────────────────────────
    logger.info(`[safety] Cache MISS for "${genericName}" — starting RAG + LLM pipeline`);

    // 5a. Fetch OpenFDA context (best-effort; empty string = LLM uses own knowledge)
    const ragContext = await fetchOpenFdaContext(genericName);

    // 5b. Generate with Gemini → Groq fallback
    let profile: object;
    try {
        profile = await generateSafetyProfile(genericName, ragContext);
    } catch (llmErr) {
        const reason = llmErr instanceof Error ? llmErr.message : String(llmErr);
        logger.error(`[safety] Both LLM providers failed for "${genericName}": ${reason}`);
        res.status(503).json({
            error: "Medicine safety data is temporarily unavailable. Please try again shortly.",
            code: "LLM_UNAVAILABLE",
        });
        return;
    }

    // ── 6. Persist to both cache layers ──────────────────────────────────────
    await setDbCachedProfile(genericName, profile);

    try {
        if (redisClient.isOpen) {
            await redisClient.set(redisCacheKey, JSON.stringify(profile), { EX: REDIS_TTL_SEC });
        }
    } catch {
        /* best-effort */
    }

    res.setHeader("X-Cache", "MISS");
    res.setHeader("X-Cache-Source", "llm-generated");
    res.json(profile);
});

export default router;
